---
name: Check

'on':
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v6
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: DeterminateSystems/flake-checker-action@v5

      - name: Check nix file formatting ❄️
        run: 'nix fmt . -- --check'
